version: "3.8"
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientdb
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: rootpass
    volumes:
        - ./mysql-db/user.sql:/docker-entrypoint-initdb.d/user.sql
    ports:
      - 3312:3306
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8095:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpass
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  Eureka:
    container_name: serviceregistry
    build: ./2alinfo1-eureka-server-ecommerce
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
  Zuul:
    container_name: Zuul
    image: "zuul"
    build: ./Zuul-Gateway
    ports:
      - "8050:8050"
    hostname: Zuul
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - "Eureka"
  stripe:
    container_name: stripe
    image: "stripepay"
    build: ./StripePaymentMicroservice
    ports:
      - "8089:8089"
    hostname: stripe
    depends_on:
      - "Eureka"
      - "Mongo"
    command: "node ./index.js"
volumes:
  data: {}
  postgres: {}
networks:
  default:
    name: mongodb_network